name: Docker Image Container Build and Push
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Increment version
        id: version
        uses: actions/github-script@v5
        with:
          script: |
            const url = `https://gitea.armstronglabs.net/api/v1/packages/bill?access_token=${{ secrets.TOKEN }}`;

            const response = await fetch(url);
            const data = await response.json();

            const tags = data.filter(tag => !tag.version.startsWith('sha'));

            const version_tags = tags.map(tag => tag.version).filter(tag => tag !== 'latest').sort().reverse();

            console.log('Version tags:', version_tags);

            const latest_version = version_tags[0];

            console.log('Last version:', latest_version);

            const version_parts = latest_version.split('.');
            const patch_version = parseInt(version_parts[2]) + 1;
            const new_version = `${version_parts[0]}.${version_parts[1]}.${patch_version}`;

            console.log('New version:', new_version);

            return new_version;
          result-encoding: string

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container registry
        uses: docker/login-action@v3
        with:
          registry: gitea.armstronglabs.net
          username: ${{ secrets.PUSH_USERNAME }}
          password: ${{ secrets.PUSH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            gitea.armstronglabs.net/bill/uploadServer:latest
            gitea.armstronglabs.net/bill/uploadServer:${{ steps.version.outputs.result }}
            
      - name: Inspect 
        run: |
          docker buildx imagetools inspect gitea.armstronglabs.net/bill/uploadServer:latest
          docker buildx imagetools inspect gitea.armstronglabs.net/bill/uploadServer:${{ steps.version.outputs.result }}
