apiVersion: v1
kind: Service
metadata:
  labels:
    app: upload-server-app
  name: upload-server-app
  namespace: ethan
spec:
  ports:
  - nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
    name: html

  selector:
    app: upload-server-app
  type: NodePort