name: Docker Image Container Build and Push
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Increment version
        id: version
        uses: actions/github-script@v5
        with:
          script: |
            const url = `https://registry.hub.docker.com/v2/repositories/explosion33/upload-server/tags`;

            const response = await fetch(url);
            const data = await response.json();

            const tags = data.results.map(result => result.name).filter(tag => !tag.startsWith('sha'));

            const version_tags = tags.filter(tag => tag !== 'latest').sort().reverse();

            console.log('Version tags:', version_tags);

            const latest_version = version_tags[0];

            console.log('Last version:', latest_version);

            const version_parts = latest_version.split('.');
            const patch_version = parseInt(version_parts[2]) + 1;
            const new_version = `${version_parts[0]}.${version_parts[1]}.${patch_version}`;

            console.log('New version:', new_version);

            return new_version;
          result-encoding: string

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            explosion33/upload-server:latest
            explosion33/upload-server:${{ steps.version.outputs.result }}
            
      - name: Inspect 
        run: |
          docker buildx imagetools inspect explosion33/upload-server:latest
          docker buildx imagetools inspect explosion33/upload-server:${{ steps.version.outputs.result }}
